#!name=获取StormSnifferHeader
#!desc=获取StormSnifferHeader
#脚本作者:PayNe

[Script]

StormSnifferCrack_3 = type=http-response,pattern="^http[s]?:\/\/api\.x-storm\.com(:\d{2,5})?\/app/((user-profile\/)|(auth-device\/list\/))$",requires-body=true,max-size=3145728,script-path= https://raw.githubusercontent.com/xuchaoqaq/Diudiu/main/Surge/JS/StormSnifferHeader.js,timeout=60,script-update-interval=0


[MITM]

hostname = %APPEND% *.x-storm.com
